version: '2'

services:
  postgres:
    image: postgres:9.4.5
    environment:
      POSTGRES_USER: mobydock
      POSTGRES_PASSWORD: yourpassword
    ports:
      - '5432:5432'
    volumes:
      - mobydock-postgres:/var/lib/postgresql/data

  redis:
    image: redis:2.8.22
    ports:
      - '6379:6379'
    volumes:
      - mobydock-redis:/var/lib/redis/data

  mobydock:
    build: .
    # this seems to help a little bit with race conditions where
    # postgres is not ready yet when rails starts
    # command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; rake db:migrate'

    ports:
      - '8000:8000'
    env_file:
      - .mobydock.env

volumes:
  mobydock-postgres:
  mobydock-redis:
